name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'build.gradle'
      - 'build.properties'
      - '*/build.gradle'
      - '*/build.properties'
  pull_request:
    paths:
      - '*/src/**'
      - '*/build.gradle'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle
            **/build.properties
            **/gradle.properties

      - name: Build
        run: ./gradlew build

      - name: Move build artifacts to one directory
        run: |
          mkdir build
          mkdir build/libs
          mv */build/libs/*.jar build/libs -v

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/
          if-no-files-found: error
